version: "3.8"
services:
    apache:
      container_name: apache
      image: 'bitnami/apache:latest'
      ports:
        - '8000:80'
        - '443:8443'
      volumes:
        - /path/to/app:/app 
      links: 
        - db:db
        - phpmyadmin:phpmyadmin
      networks: 
        - db_network
    db:
        container_name: mysql
        hostname: mysql
        image: mysql
        ports:
          - "3306:3306"
        environment:
          MYSQL_DATABASE: mabDB
          MYSQL_USER: mab
          MYSQL_PASSWORD: mab07
          MYSQL_ROOT_PASSWORD: mab07
        volumes:
          - persistent:/var/lib/mysql
          - ./files:/files
        networks:
          - db_network

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        hostname: pma
        links:
          - db:db
        ports:
          - 8000:80
        environment:
          MYSQL_USER: mab
          MYSQL_PASSWORD: mab07
          MYSQL_ROOT_PASSWORD: mab07
        networks: 
          - db_network
volumes:
    persistent:

networks: 
  db_network:
    name: db_network